### PR TITLE
Fix #25

### LINKED ISSUE #25: tc_upset bug
Casualties or vehicles are not being properly assigned to the 'Other' category. 

The figure in the function help example has lots of accidents with lone pedestrians or with lone cyclists. This isn't correct. Instead these crashes should probably be 'pedestrian + other' and 'cyclist + other.'

```
remotes::install_github("saferactive/trafficalmr")
library(trafficalmr)
remotes::install_github("krassowski/complex-upset")

crash_summary = tc_join_stats19(crashes_wf, casualties_wf, vehicles_wf)


# create plot with 'Other' category
casualties_wf2 = dplyr::mutate(
  casualties_wf,
  casualty_type_simple = dplyr::case_when(
    casualty_type == "Car occupant" ~ "Car",
    casualty_type == "Pedestrian" ~ "Pedestrian",
    casualty_type == "Cyclist" ~ "Cyclist",
    TRUE ~ "Other"
  )
)
crash_summary = tc_join_stats19(crashes_wf, casualties_wf2, vehicles_wf)
tc_upset(crash_summary, casualty_type = c("Car", "Pedestrian", "Bicycle", "Other"))
```

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

File: R/upset.R [hunk 1]
```diff
@@ -21,7 +21,16 @@
 #'      TRUE ~ "Other"
 #'     )
 #'   )
-#' crash_summary = tc_join_stats19(crashes_wf, casualties_wf2, vehicles_wf)
+#' table(vehicles_wf$vehicle_type)
+#' vehicles_wf2 = dplyr::mutate(
+#'   vehicles_wf,
+#'   vehicle_type_simple = dplyr::case_when(
+#'      vehicle_type == "Car" ~ "Car",
+#'      vehicle_type == "Cyclist" ~ "Pedal cycle",
```
Comment (joeytalbot) [inline R/upset.R]: How come vehicle type here is "Pedal cycle", but on the upset plot it's "bicycle"?

Comment (Robinlovelace) [reply R/upset.R]: Good question and well spotted. I think for casualties it's because of this line:

https://github.com/saferactive/trafficalmr/blob/bce0785abcb3df34a9e16d3594563b5f28a82536/R/upset.R#L122

I don't see an equivalent for "Pedal cycle" so have updated the example accordingly. Great fix!
